### ISSUE TITLE
selected disabled doesn't work

### ISSUE THREAD

**Issue by corientdev** [FezVrasta/dropdown.js#17]
selected disabled doesn't work. I.e it doesn't disable the selection of disabled option

**Comment by cromartie1984** [comment]
any news on this?

**Comment by FezVrasta** [comment]
PRs are always welcome

**Comment by corientdev** [comment]
I am willing to do this can you please guide me a bit @FezVrasta

**Comment by FezVrasta** [comment]
This should be the check:
https://github.com/FezVrasta/dropdown.js/blob/master/jquery.dropdown.js#L227

I guess the selector doesn't catch the disabled state properly.

**Comment by corientdev** [comment]
Its kinda complicated will see this weekend

**Comment by corientdev** [comment]
@FezVrasta  can you please transfer the ownership of this wonderful plugin? I will maintain it

**Comment by FezVrasta** [comment]
I'd rather keep it under my namespace because I have some plans for it once I'll have some free time to work on it. Feel free to contribute with PRs, I'll try to merge them ASAP.
