### ISSUE TITLE
"dropdownClass" and "optionClass" doesn't add to dropdown.

### ISSUE THREAD

**Issue by samsam2310** [FezVrasta/dropdown.js#21]
I try to added some class to dropdown with
```
$(".select").dropdown({ "dropdownClass": "my-dropdown", "optionClass": "my-option awesome" });
```
but it didn't work.
What's wrong?
Thanks.

**Comment by jbgarr** [comment]
+1 Same issue for me.

**Comment by rku4er** [comment]
Have you read this https://github.com/FezVrasta/dropdown.js/issues/19#event-345365505
