### ISSUE TITLE
Does not function properly in Safari 

### ISSUE THREAD

**Issue by nekkon** [FezVrasta/dropdown.js#23]
Tried using dropdown in http://fezvrasta.github.io/bootstrap-material-design/#dropdown-menu and did not work properly in Safari..

![screen shot 2015-07-31 at 11 12 01 am](https://cloud.githubusercontent.com/assets/8094269/9003240/ff2d33e4-3774-11e5-893c-826df3edfe4a.png)

**Comment by greenteamer** [comment]
same problem

**Comment by FezVrasta** [comment]
Looks like we miss the vendor prefix which is required by Safari. I'll run autoprefix to our css and fix it.

**Comment by FezVrasta** [comment]
Now it should work.
Give time to the CDN to update itself to see the demo updated.
