### ISSUE TITLE
Have any example?

### ISSUE THREAD

**Issue by thearabbit** [FezVrasta/dropdown.js#33]
Have any example?

**Comment by FezVrasta** [comment]
Here an example:
http://fezvrasta.github.io/bootstrap-material-design/#dropdown-menu

The "arrow icon" is broken there because one of the contributors is making some changes to the theme.

**Comment by Keziolio** [comment]
>The "arrow icon" is broken there because one of the contributors is making some changes to the theme.

You mean the thing at the end of the input? It's broken also in my project, can you please tell how to remove that?

Thanks

**Comment by FezVrasta** [comment]
You should be able to disable or change the symbol displayed tweaking:

```.dropdownjs > ul > li > .close:before ```

**Comment by thearabbit** [comment]
Thanks for your reply.
But we can't search like `select2`.

**Comment by thearabbit** [comment]
This is `dropdown menu`, not `dropdown`.

**Comment by FezVrasta** [comment]
If there's a feature you would like, just send a PR to implement it.
