### ISSUE TITLE
Only one option can be selected in multiselect

### ISSUE THREAD

**Issue by Sachiano** [FezVrasta/dropdown.js#35]
With a multiselect dropdown, whenever an item is selected, the previous selection on the actual `<select>` input is cleared. The plugin's styling keeps all the items highlighted as if they are still selected.

My `<select>` element markup:

    <select name="categories[]" id="categories-dropdown" class="select form-control" multiple="true" placeholder="Select one or more categories">
        [...]options[...]
    </select>
</div>

The JavaScript:

    $("select").dropdown({
        "autoinit": "select",
        "optionClass": "withripple"
    });

I suspect I may be doing something wrong?

[Here is a video demonstrating the selected options being unselected.](https://gfycat.com/RingedWeeCanine)

**Comment by neuropass** [comment]
any word of this one? Its quite important the multiselect :-/ Pls look into it.

**Comment by FezVrasta** [comment]
Sorry I'm not actively maintaining this project anymore. Pull Requests are welcome.

**Comment by neuropass** [comment]
oh come on! what about this:

"Finally a dropdown plugin that transforms select inputs in nice dropdowns and does not drive you crazy.
I've always wondered why the most famous plugins (Chosen and Selectize) are so huge and full of useless/pointless features? What do you need from a dropdown plugin?"


please.

**Comment by FezVrasta** [comment]
I'm sorry I've a lot of other work to do and I'm not working anymore with jQuery. I'm focused on React now. 😔
