### ISSUE TITLE
onSelected gets fired twice when clicked due

### ISSUE THREAD

**Issue by chtrinh** [FezVrasta/dropdown.js#42]
@FezVrasta I'm not sure what the purpose of this line 
https://github.com/FezVrasta/dropdown.js/blob/master/jquery.dropdown.js#L132

The comments indicates a condition but there is none listed. What was the intentions here? 
Currently the behavior is user clicks on selected item `methods._select()` gets fired twice due to `$select.change()`

**Comment by FezVrasta** [comment]
It could be the result of some PR... a PR to fix it is welcome

**Comment by neuropass** [comment]
Can you merge this pls? @FezVrasta
