### ISSUE TITLE
on change event not firing

### ISSUE THREAD

**Issue by NoelChew** [FezVrasta/dropdown.js#5]
Can you show me how to trigger the onChange event with 'form-control' class?
There seems to be a problem triggering the on change event when dropdown.js is used.

**Comment by FezVrasta** [comment]
It should already trigger the change event.
But is bugged... lol

https://github.com/FezVrasta/dropdown.js/blob/master/jquery.dropdown.js#L113

I've written `.change()` instead of `.trigger('change')`.

If you wanna send a PR is welcome, otherwise I'll do it when I can.

**Comment by NoelChew** [comment]
My apologies, I wasn't having the latest dropdownjs. In the previous version, '.change()' didn't exist. Now it is working fine. Thanks!
