### ISSUE TITLE
Issue with value on IE

### ISSUE THREAD

**Issue by poornimanayar** [FezVrasta/dropdown.js#52]
I have a dropdown where some of the values goes "4 to 6 months" , "7 to 11 months" and so on. I have noticed that when the value of the li gets set it sets it as 4, 7 etc and gets rid of the rest of the string. I am sure that this is not an issue with the plugin but more IE. Have you got any thoughts on this?

Poornima

**Comment by FezVrasta** [comment]
Provide a working codepen.io example please.

**Comment by poornimanayar** [comment]
Hi,

Thanks a lot for getting back to me. We will provide you with some links where this happens.

Poornima
