### ISSUE TITLE
IE/Edge specfic issue

### ISSUE THREAD

**Issue by poornimanayar** [FezVrasta/dropdown.js#53]
#52 I have a dropdown where some of the values goes "4 to 6 months" , "7 to 11 months" and so on. I have noticed that when the value of the li gets set it sets it as 4, 7 etc and gets rid of the rest of the string. I am sure that this is not an issue with the plugin but more IE. 

You asked for a working example and here is the link to it http://cvtus-u7.assiduusinc.com/forms/enroll-in-meplus/

If you try submitting the form with the "Surgery Date" selected as "4 to 6 months" or "7 to 11 months" you can see it wont submit on Edge/IE but it will on other browsers. Inspecting the HTML shows that value for the <li> in this case on Edge/IE is "4" and "7" respectively. 

Is there any workaround to achieve same HTML across the browsers?

Poornima

**Comment by FezVrasta** [comment]
Sorry, I asked for a codepen.io example, with a reduced test case. I'm not going to debug your application. Feel free to reply here with the needed test case and I'll be happy to re-open the issue.
