### ISSUE TITLE
Download through NPM?

### ISSUE THREAD

**Issue by Isabellle** [FezVrasta/dropdown.js#60]
I haven't found the command line to download it using NPM.
Can anyone share it with me?

Thanks!

**Comment by Peeeep** [comment]
`npm install https://github.com/FezVrasta/dropdown.js/tarball/master`

or

`npm install https://github.com/FezVrasta/dropdown.js/tarball/0.0.2-dev`

**Comment by FezVrasta** [comment]
`npm install FezVrasta/dropdown.js` should do the trick as well.
