### ISSUE TITLE
This material drop-down are not supporting autocomplete ? 

### ISSUE THREAD

**Issue by atifdmv** [FezVrasta/dropdown.js#65]
I want to add autocomplete functionality, how can I use that?

**Comment by FezVrasta** [comment]
Find a plug-in

**Comment by atifdmv** [comment]
Can you please provide any link of plug-in?

**Comment by FezVrasta** [comment]
Nope sorry. This library isn't maintained anymore. Find a different hurry plugin to achieve what you need
